#
# Product-specific compile-time definitions.
#

-include vendor/telechips/tcc8902/BoardConfigVendor.mk

# The above file contains our proprietare stuff and is generated by extract-files.sh which calls setup-makefiles.sh

TARGET_BOARD_PLATFORM := intrinsity
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := tcc8902
TARGET_NO_RADIOIMAGE := true

BOARD_KERNEL_CMDLINE := console=ttySAC0 androidboot.hardware=tcc92xx
BOARD_KERNEL_BASE := 0x40000000
BOARD_PAGE_SIZE := 0x00001000

# We still need to verify actual max sizes versus real rom.
BOARD_BOOTIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x00280000)
BOARD_RECOVERYIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x00500000)
BOARD_SYSTEMIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x07500000)
BOARD_USERDATAIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x04ac0000)

# The size of a block that can be marked bad.
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../vendor/telechips/tcc8902/default_recovery_ui.c

# Audio is using ALSA sound but no clue how to set that up yet.
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
#BOARD_USES_GENERIC_AUDIO := false

# Camera needs to be disabled
USE_CAMERA_STUB := true

# Disable Bluetooth for now
BOARD_HAVE_BLUETOOTH := false

# Wifi related defines (need to be fixed, as we have prebuilt kernel, w/ no source.
# There is an AR6000 on board, we have working modules and stuff under 2.1 :)
#BOARD_WPA_SUPPLICANT_DRIVER := AWEXT
#BOARD_WPA_SUPPLICANT_PRIVATE_LIB := libWifiApi
#BOARD_WLAN_TI_STA_DK_ROOT := system/wlan/ti/sta_dk_4_0_4_32
#WIFI_DRIVER_MODULE_PATH := "/system/wifi/ar6000.ko"
#WIFI_DRIVER_MODULE_ARG := ""
#WIFI_DRIVER_MODULE_NAME := "ar6000"

ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0